on:
  push:
    branches:
      - main
      - maste
jobs:
  job1:
    runs-on: ubuntu-latest
    name: cran log data update
    container: rocker/verse
    steps:
      - uses: actions/checkout@v2
      - run: Rscript ./cran_logs/restatapi_logs.R
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: updating restatapi logs files
      
